# Generated by Django 5.2.4 on 2026-08-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banner_img", models.ImageField(upload_to="banners/%Y/%m/%d/")),
                ("alt_text", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name_plural": "Banners",
            },
        ),
    ]
